# -*- ruby -*-

# require 'autotest/autoupdate'
# require 'autotest/fixtures'
# require 'autotest/growl'
# require 'autotest/html_report'
# require 'autotest/kdenotify'
# require 'autotest/menu'
# require 'autotest/migrate'
# require 'autotest/notify'
# require 'autotest/pretty'
# require 'autotest/redgreen'
# require 'autotest/screen'
# require 'autotest/shame'
# require 'autotest/snarl'
# require 'autotest/timestamp'
